templates_en = [
    lambda c: f'a photo of many {c}.',
    lambda c: f'a sculpture of a {c}.',
    lambda c: f'a rendering of a {c}.',
    lambda c: f'a cropped photo of the {c}.',
    lambda c: f'the embroidered {c}.',
    lambda c: f'a photo of a clean {c}.',
    lambda c: f'a photo of a dirty {c}.',
    lambda c: f'a dark photo of the {c}.',
    lambda c: f'a drawing of a {c}.',
    lambda c: f'a photo of my {c}.',
    lambda c: f'a photo of the cool {c}.',
    lambda c: f'a close-up photo of a {c}.',
    lambda c: f'a black and white photo of the {c}.',
    lambda c: f'a sculpture of the {c}.',
    lambda c: f'a bright photo of the {c}.',
    lambda c: f'a cropped photo of a {c}.',
    lambda c: f'a photo of the dirty {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a good photo of the {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'a photo of one {c}.',
    lambda c: f'a close-up photo of the {c}.',
    lambda c: f'a photo of a {c}.',
    lambda c: f'the {c} in a video game.',
    lambda c: f'a low resolution photo of a {c}.',
    lambda c: f'the toy {c}.',
    lambda c: f'a photo of the clean {c}.',
    lambda c: f'a photo of a large {c}.',
    lambda c: f'a photo of a nice {c}.',
    lambda c: f'a photo of a weird {c}.',
    lambda c: f'a good photo of a {c}.',
    lambda c: f'a photo of the nice {c}.',
    lambda c: f'a photo of the small {c}.',
    lambda c: f'a photo of the weird {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a black and white photo of a {c}.',
    lambda c: f'a dark photo of a {c}.',
    lambda c: f'a toy {c}.',
    lambda c: f'a photo of a cool {c}.',
    lambda c: f'a photo of a small {c}.'
]


templates_fr = [
    lambda c: f'une photo de plusieurs {c}.',
    lambda c: f'une sculpture de {c}.',
    lambda c: f"une sculpture d'un {c}.",
    lambda c: f"une sculpture d'une {c}.",
    lambda c: f'une représentation de {c}.',
    lambda c: f"une représentation d'un {c}.",
    lambda c: f"une représentation d'une {c}.",
    lambda c: f'une photo coupée de {c}.',
    lambda c: f"une photo coupée d'un {c}.",
    lambda c: f"une photo coupée d'une {c}.",
    lambda c: f'le {c} brodé.',
    lambda c: f'une photo propre de {c}.',
    lambda c: f"une photo propre d'un {c}.",
    lambda c: f"une photo propre d'une {c}.",
    lambda c: f'une photo sale de {c}.',
    lambda c: f"une photo sale d'un {c}.",
    lambda c: f"une photo sale d'une {c}.",
    lambda c: f'une photo sombre de {c}.',
    lambda c: f"une photo sombre d'un {c}.",
    lambda c: f"une photo sombre d'une {c}.",
    lambda c: f'un dessin de {c}.',
    lambda c: f"un dessin d'un {c}.",
    lambda c: f"un dessin d'une {c}.",
    lambda c: f'une photo de mon {c}.',
    lambda c: f'une photo de ma {c}.',
    lambda c: f'une photo cool de {c}.',
    lambda c: f"une photo cool d'un {c}.",
    lambda c: f"une photo cool d'une {c}.",
    lambda c: f'une photo rapproché de {c}.',
    lambda c: f"une photo rapproché d'un {c}.",
    lambda c: f"une photo rapproché d'une {c}.",
    lambda c: f'une photo noire et blanc de {c}.',
    lambda c: f"une photo noire et blanc d'un {c}.",
    lambda c: f"une photo noire et blanc d'une {c}.",
    lambda c: f'une photo claire de {c}.',
    lambda c: f"une photo claire d'un {c}.",
    lambda c: f"une photo claire d'une {c}.",
    lambda c: f'une photo de {c}.',
    lambda c: f"une photo d'un {c}.",
    lambda c: f"une photo d'une {c}.",
    lambda c: f'une bonne photo de {c}.',
    lambda c: f"une bonne photo d'un {c}.",
    lambda c: f"une bonne photo d'une {c}.",
    lambda c: f'le {c} dans un jeu vidéo.',
    lambda c: f'la {c} dans un jeu vidéo.',
    lambda c: f"une photo basse résolution de {c}.",
    lambda c: f"une photo basse résolution d'un {c}.",
    lambda c: f"une photo basse résolution d'une {c}.",
    lambda c: f'le jouet {c}.',
    lambda c: f"une photo d'un grand {c}.",
    lambda c: f"une photo d'une grande {c}.",
    lambda c: f"une photo d'un beau {c}.",
    lambda c: f"une photo d'une belle {c}.",
    lambda c: f"une photo bizarre de {c}.",
    lambda c: f"une photo bizarre d'un {c}.",
    lambda c: f"une photo bizarre d'une {c}.",
    lambda c: f"une photo d'un petit {c}.",
    lambda c: f"une photo d'une petite {c}.",
]
